Proposal: Add map extension to convert result values
ardalis/Result pull request #97
Opened 2022-07-15 18:50 UTC by KyleMcMaster

Fixes #81

Possibly fixes issue #94. I prefer separating `Map` and `ToActionResult` into different methods based on SRP since it is `ToActionResult`'s responsibility for mapping `Result<T> -> ActionResult<T>` rather than mapping `Result<T> -> Result<K> -> ActionResult<K>`. It is possible consumers may want to change a `Result`'s `Value` type separately of producing an `ActionResult`.

2022-07-16 17:06 UTC, joncoelloaccess commented
@KyleMcMaster looks great, thanks :)

2022-07-18 19:08 UTC, ardalis commented on src/Ardalis.Result/ResultExtensions.cs
> +        public static Result<K> Map<T, K>(this Result<T> result, Func<T, K> func)
Instead of T,K could we use names that indicate what these generic types should be? TSource, TDestination for instance?

2022-07-18 19:09 UTC, ardalis requested changes
Minor naming request. Alternate idea would be `TFrom` and `TTo` or `TFromType` / `TToType`

2022-07-18 19:40 UTC, KyleMcMaster commented on src/Ardalis.Result/ResultExtensions.cs
> +        public static Result<K> Map<T, K>(this Result<T> result, Func<T, K> func)
Updated!

2022-07-18 19:42 UTC, KyleMcMaster commented
Fixes #94

2022-07-19 18:52 UTC, ardalis approved these changes

2022-07-19 18:52 UTC, merged